const {chromium}=require('playwright');
(async()=>{const browser=await chromium.launch({headless:true});require('fs').mkdirSync('qa-browser',{recursive:true});const page=await browser.newPage({viewport:{width:1480,height:1000}});let errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:8765/');for(const tool of ['punnett','pedigree','growth','prey','gel','pipette','ph']){await page.click(`[data-tool="${tool}"]`);await page.locator('#figure svg').waitFor();await page.screenshot({path:`qa-browser/${tool}-desktop.png`,fullPage:true});console.log(tool,await page.locator('#error').isVisible()?'ERROR':'rendered');let dlPromise=page.waitForEvent('download');await page.click('#svg');const dl=await dlPromise;await dl.saveAs(`qa-browser/${tool}-test.svg`);}
await page.click('[data-tool="punnett"]');await page.selectOption('#f-cross','x');await page.locator('#figure svg').waitFor();await page.fill('#f-parent1','bad');await page.locator('#f-parent1').dispatchEvent('change');if(!await page.locator('#error').isVisible())throw Error('Invalid input not caught');await page.click('#reset');
let dlp=page.waitForEvent('download');await page.click('#png');const dl=await dlp;await dl.saveAs('qa-browser/export-test.png');
await page.click('[data-tool="prey"]');await page.selectOption('#f-view','phase');await page.selectOption('#f-model','limited');await page.locator('#figure svg').waitFor();await page.screenshot({path:'qa-browser/prey-phase.png'});
await page.click('[data-tool="ph"]');for(const method of ['strong','weak','buffer']){await page.selectOption('#f-method',method);if(await page.locator('#error').isVisible())throw Error('pH error '+method);}
await page.click('[data-tool="pipette"]');await page.selectOption('#f-exercise','precision');await page.locator('#check-reading').waitFor();
for(const tool of ['punnett','pedigree','growth','prey','gel','pipette','ph']){await page.setViewportSize({width:390,height:844});await page.click(`[data-tool="${tool}"]`);const width=await page.evaluate(()=>document.documentElement.scrollWidth);if(width>390)throw Error(`Mobile overflow ${tool}: ${width}`);await page.screenshot({path:`qa-browser/${tool}-mobile.png`,fullPage:true});}
console.log('Browser errors:',JSON.stringify(errors));if(errors.length)throw Error(errors.join('\n'));await browser.close();})();
