/* EAHS Science: original educational models. All numerical functions are DOM-independent. */
(function(root){
'use strict';
const canonical=(a,b)=>[a,b].sort((x,y)=>x===x.toUpperCase()&&y!==y.toUpperCase()?-1:y===y.toUpperCase()&&x!==x.toUpperCase()?1:x.localeCompare(y)).join('');
function gametes(g){const pairs=g.match(/.{2}/g);if(!pairs||![2,4].includes(g.length)||pairs.some((p,i)=>!new RegExp(i?'^[Bb]{2}$':'^[Aa]{2}$').test(p)))throw Error('Use AA, Aa, aa or two loci in A then B order (for example AaBb).');let out=[''];for(const p of pairs)out=out.flatMap(x=>[x+p[0],x+p[1]]);return out;}
function punnett(s){let a,b,combine,phenotype;
if(s.cross==='x'){if(!/^(AA|Aa|aA|aa)$/.test(s.parent1)||!/^([Aa])Y$/.test(s.parent2))throw Error('For X-linked crosses, enter the female as AA, Aa or aa and the male as AY or aY.');a=s.parent1.split('');b=s.parent2.split('');combine=(x,y)=>y==='Y'?`X${x}Y`:`X${canonical(x,y)[0]}X${canonical(x,y)[1]}`;phenotype=g=>g.endsWith('Y')?(g[1]==='a'?'Affected male':'Unaffected male'):(g[1]==='a'&&g[3]==='a'?'Affected female':g[1]!==g[3]?'Carrier female':'Noncarrier female');}
else{a=gametes(s.parent1);b=gametes(s.parent2);if(s.parent1.length!==s.parent2.length)throw Error('Parents must have the same number of loci.');if(s.cross!=='complete'&&s.parent1.length!==2)throw Error('Incomplete dominance and codominance use one locus (AA, Aa or aa).');combine=(x,y)=>x.split('').map((v,i)=>canonical(v,y[i])).join('');phenotype=g=>s.cross==='incomplete'?(g==='Aa'?'Intermediate heterozygote':g==='AA'?'A homozygote':'a homozygote'):s.cross==='codominant'?(g==='Aa'?'Both allele products':g==='AA'?'A product':'a product'):g.match(/.{2}/g).map((p,i)=>`${'AB'[i]} ${p.includes('AB'[i])?'dominant':'recessive'}`).join(' / ');}
const cells=a.map(x=>b.map(y=>combine(x,y))),counts={},ph={};cells.flat().forEach(g=>{counts[g]=(counts[g]||0)+1;let p=phenotype(g);ph[p]=(ph[p]||0)+1});const total=a.length*b.length;return{a,b,cells,genotypes:Object.entries(counts).map(([g,n])=>[g,n/total]),phenotypes:Object.entries(ph).map(([g,n])=>[g,n/total]),total};}
function growth(s){const rows=[];for(let i=0;i<=400;i++){let t=s.time*i/400,e=Math.exp(-s.r*t);let n=s.model==='logistic'?s.k/(1+(s.k/s.n0-1)*e):s.n0*Math.exp(s.r*t);let rate=s.r*n*(s.model==='logistic'?1-n/s.k:1);if(!Number.isFinite(n)||n>1e12)throw Error('Population exceeds the plotting limit (10¹²). Reduce r or time.');rows.push([t,n,rate,n?rate/n:0]);}return rows;}
function derivative(v,s){let [x,y]=v;return[s.alpha*x*(s.model==='limited'?1-x/s.k:1)-s.beta*x*y,s.delta*x*y-s.gamma*y];}
function rk4(v,h,s){const a=derivative(v,s),b=derivative(v.map((x,i)=>x+h*a[i]/2),s),c=derivative(v.map((x,i)=>x+h*b[i]/2),s),d=derivative(v.map((x,i)=>x+h*c[i]),s);return v.map((x,i)=>x+h*(a[i]+2*b[i]+2*c[i]+d[i])/6);}
function prey(s,steps=12000){let v=[s.prey0,s.pred0],rows=[[0,...v]],h=s.time/steps;for(let i=1;i<=steps;i++){v=rk4(v,h,s);if(v.some(x=>!Number.isFinite(x)||x<0||x>1e9))throw Error('These rates exceed the numerical solver range. Reduce rates, populations or time.');if(i%Math.max(1,Math.round(steps/600))===0)rows.push([i*h,...v]);}return rows;}
const people=[{id:'I-1',sex:'m'},{id:'I-2',sex:'f'},{id:'II-1',sex:'f',parents:[0,1]},{id:'II-3',sex:'m',parents:[0,1]},{id:'II-2',sex:'m'},{id:'II-4',sex:'f'},{id:'III-1',sex:'m',parents:[4,2]},{id:'III-2',sex:'f',parents:[4,2]},{id:'III-3',sex:'m',parents:[3,5]},{id:'III-4',sex:'f',parents:[3,5]}];
const modes=['AR','AD','XLR','XLD','Y'];
function domain(mode,sex){return mode==='Y'?(sex==='m'?['0','1']:['0']):mode.startsWith('X')&&sex==='m'?['AY','aY']:['AA','Aa','aa'];}
function affected(mode,g,sex){if(mode==='Y')return g==='1';return mode==='AR'||mode==='XLR'?g==='aa'||g==='aY':g.includes('A');}
function childProb(mode,sex,g,f,m){if(mode==='Y')return g===(sex==='m'?f:'0')?1:0;if(mode.startsWith('X')){const maternal=m.split(''),p=sex==='m'?maternal.map(a=>a+'Y'):maternal.map(a=>canonical(f[0],a));return p.filter(x=>x===g).length/2;}let n=0;for(const a of f)for(const b of m)if(canonical(a,b)===g)n++;return n/4;}
function pedigree(mode,status){const sums=people.map(()=>({})),possible=people.map(()=>new Set()),assignment=[],domains=people.map((p,i)=>domain(mode,p.sex).filter(g=>status[i]==='unknown'||affected(mode,g,p.sex)===(status[i]==='affected')));let weight=0,count=0;
function walk(i,w){if(i===people.length){count++;weight+=w;assignment.forEach((g,j)=>{possible[j].add(g);sums[j][g]=(sums[j][g]||0)+w});return;}for(const g of domains[i]){const ps=people[i].parents;const pr=ps?childProb(mode,people[i].sex,g,assignment[ps[0]],assignment[ps[1]]):1/domain(mode,people[i].sex).length;if(pr){assignment[i]=g;walk(i+1,w*pr);}}}walk(0,1);return{mode,count,weight,possible:possible.map(x=>Array.from(x)),probabilities:sums.map(x=>Object.fromEntries(Object.entries(x).map(([g,w])=>[g,w/weight])))};}
function randomPedigree(mode){const gs=[];people.forEach((p,i)=>{let dom=domain(mode,p.sex);if(!p.parents)gs[i]=dom[Math.floor(Math.random()*dom.length)];else{let r=Math.random(),sum=0;gs[i]=dom.find(g=>{sum+=childProb(mode,p.sex,g,gs[p.parents[0]],gs[p.parents[1]]);return r<sum})||dom.at(-1);}});return gs.map((g,i)=>affected(mode,g,people[i].sex)?'affected':'unaffected');}
function fragments(s){const parse=(text)=>{const ns=text.split(/[ ,;]+/).filter(Boolean).map(Number);if(!ns.length||ns.length>25||ns.some(x=>!Number.isFinite(x)||x<100||x>10000))throw Error('Each lane needs 1–25 sizes between 100 and 10,000 bp.');return ns.sort((a,b)=>b-a);};const lanes=s.lanes.split('\n').filter(x=>x.trim()).map((line,i)=>{let split=line.indexOf(':');let name=split<0?`Sample ${i+1}`:line.slice(0,split).trim();return{name:name.slice(0,18),sizes:parse(split<0?line:line.slice(split+1))};});if(!lanes.length||lanes.length>6)throw Error('Enter 1–6 sample lanes, one per line.');return[{name:'Ladder',sizes:parse(s.ladder)},...lanes];}
function migration(bp,run){return 12+run*(4-Math.log10(bp))/2;}
const pipettes={P20:{min:2,max:20,step:.1,factor:10,places:['10 µL','1 µL','0.1 µL']},P200:{min:20,max:200,step:1,factor:1,places:['100 µL','10 µL','1 µL']},P1000:{min:100,max:1000,step:10,factor:.1,places:['1000 µL','100 µL','10 µL']}};
function pipette(s){const p=pipettes[s.instrument];if(s.volume<p.min||s.volume>p.max||Math.abs(s.volume/p.step-Math.round(s.volume/p.step))>1e-6)throw Error(`Use ${p.min}–${p.max} µL in ${p.step} µL steps for ${s.instrument}.`);const n=Math.round(s.volume*p.factor);return{...p,digits:String(n).padStart(3,'0'),ml:s.volume/1000};}
function measurement(text,target){const a=text.split(/[ ,;\n]+/).filter(Boolean).map(Number);if(a.length<2||a.length>100||a.some(x=>!Number.isFinite(x)||x<=0))throw Error('Enter 2–100 positive replicate measurements.');const mean=a.reduce((a,b)=>a+b,0)/a.length,sd=Math.sqrt(a.reduce((s,x)=>s+(x-mean)**2,0)/(a.length-1));return{mean,sd,cv:100*sd/mean,bias:100*(mean-target)/target,n:a.length};}
function ph(s){let h;if(s.method==='direct')h=10**(-s.ph);else if(s.method==='strong'){h=(s.conc+Math.sqrt(s.conc*s.conc+4e-14))/2;}else if(s.method==='weak'){// Charge balance H = C*Ka/(Ka+H) + Kw/H; solve in log space.
let lo=-14,hi=Math.log10(s.conc+1);for(let i=0;i<100;i++){let mid=(lo+hi)/2,H=10**mid;if(H-s.conc*s.ka/(s.ka+H)-1e-14/H>0)hi=mid;else lo=mid;}h=10**((lo+hi)/2);}else h=10**(-(s.pka+Math.log10(s.base/s.acid)));return{h,oh:1e-14/h,ph:-Math.log10(h),poh:-Math.log10(1e-14/h),ratio:h/10**(-s.reference)};}
const M={gametes,punnett,growth,derivative,rk4,prey,people,modes,domain,affected,childProb,pedigree,randomPedigree,fragments,migration,pipettes,pipette,measurement,ph};root.Models=M;if(typeof module!=='undefined')module.exports=M;
})(typeof window==='undefined'?globalThis:window);
