'use strict';
(()=>{
 const KEY='eahs-learning-journal-v1';
 let journal={version:1,activities:{}},storageOK=true;
 const copy=x=>JSON.parse(JSON.stringify(x));
 try{let saved=JSON.parse(localStorage.getItem(KEY)||'null');if(saved&&saved.version===1&&saved.activities&&typeof saved.activities==='object'&&!Array.isArray(saved.activities))journal=saved;}catch{storageOK=false;}
 function record(){if(!journal.activities[current]||!Array.isArray(journal.activities[current].observations))journal.activities[current]={phase:'predict',response:'',reason:'',explanation:'',design:'',observations:[],checklist:[],state:copy(states[current])};return journal.activities[current];}
 function save(){record().state=copy(states[current]);try{localStorage.setItem(KEY,JSON.stringify(journal));storageOK=true;}catch{storageOK=false;}$('learning-save').textContent=storageOK?'Saved in this browser. Export your journal before changing devices.':'Browser storage is unavailable or full. Keep this page open and export your journal.';}
 const sameSettings=(a,b)=>tools[current].fields.filter(f=>!['view','display','labels','filled','preyName','predName'].includes(f.key)).every(f=>a[f.key]===b[f.key])&&JSON.stringify(a.status)===JSON.stringify(b.status);
 function lock(){const r=record(),locked=r.phase==='predict';document.body.classList.toggle('prediction-locked',locked);document.querySelectorAll('#fields input,#fields select,#fields textarea,#fields button').forEach(e=>e.disabled=locked);$('reset').disabled=locked;$('results').hidden=r.phase!=='review';$('lesson').hidden=locked;$('figure').setAttribute('aria-hidden',String(locked));document.querySelector('.export-bar').hidden=locked;document.querySelectorAll('#png,#svg,#print,#csv,#share').forEach(e=>{e.disabled=locked||(e.id==='csv'&&!data.length)});$('learning-lock').hidden=!locked;$('observe-panel').hidden=locked;$('explain-panel').hidden=locked;$('review-panel').hidden=r.phase!=='review';$('predict-button').hidden=!locked;if($('prediction-response'))$('prediction-response').disabled=!locked;$('prediction-reason').disabled=!locked;$('stage-label').textContent=locked?'1 · Predict':r.phase==='review'?'4 · Review':'2–3 · Investigate & explain';document.querySelectorAll('#tools button').forEach(b=>{const a=journal.activities[b.dataset.tool];b.classList.toggle('activity-done',a?.completed===true);});}
 function sampledRows(rows){if(rows.length<=122)return copy(rows);return copy([rows[0],...Array.from({length:121},(_,i)=>rows[1+Math.round(i*(rows.length-2)/120)])]);}
 function observations(){const r=record();$('evidence-list').innerHTML=r.observations.length?r.observations.map((o,i)=>'<details><summary>Observation '+(i+1)+' · '+esc(o.note.slice(0,100))+'</summary><p>'+esc(o.note)+'</p><dl>'+tools[current].fields.map(f=>'<dt>'+esc(f.label)+'</dt><dd>'+esc(o.state[f.key])+'</dd>').join('')+'</dl><button class="remove-observation" data-index="'+i+'">Remove observation</button></details>').join(''):'<p class="micro">No evidence recorded yet. Capture at least two distinct settings and describe what you observe.</p>';$('evidence-list').querySelectorAll('.remove-observation').forEach(b=>b.onclick=()=>{r.observations.splice(Number(b.dataset.index),1);r.completed=false;if(r.phase==='review')r.phase='explore';save();observations();lock();});}
 function feedback(){const r=record(),c=LearningChallenges.get(current,tools[current]),g=LearningChallenges.grade(c,r.baseline||states[current],r.response);let expected=g.expected===undefined?'':c.kind==='choice'?c.options[g.expected]:fmt(g.expected)+' '+c.unit;$('feedback').innerHTML='<p><strong>'+esc(g.message)+'</strong></p>'+(expected?'<p>Starting-condition model answer: <strong>'+esc(expected)+'</strong>'+(c.kind==='number'?'. Estimate tolerance: '+(c.tolerance*100)+'% of a nonzero answer. This is a learning check, not a course grade.':'')+'</p>':'')+'<p>'+esc(c.rationale)+'</p><p>Your written explanation is saved for self-review or teacher discussion. It has not been automatically graded.</p>';$('baseline-settings').innerHTML='<summary>Starting conditions used for feedback</summary><dl>'+tools[current].fields.map(f=>'<dt>'+esc(f.label)+'</dt><dd>'+esc((r.baseline||states[current])[f.key])+'</dd>').join('')+'</dl>';$('activity-status').textContent=r.completed?'Investigation completed and saved.':'Check your explanation against the criteria below.';}
 function mount(){let r=record(),t=tools[current],c=LearningChallenges.get(current,t);$('learning-title').textContent='Your investigation';$('learning-description').textContent=t.sub;$('learning-goal').textContent=t.prompt;$('prediction-question').textContent=c.question;$('prediction-unit').textContent=c.unit||'Use a testable statement.';let response=$('response-slot');response.innerHTML=c.kind==='choice'?'<select id="prediction-response"><option value="">Choose a prediction…</option>'+c.options.map((o,i)=>'<option value="'+i+'">'+esc(o)+'</option>').join(''):'<'+(c.kind==='written'?'textarea':'input')+' id="prediction-response" '+(c.kind==='written'?'rows="3" maxlength="2000"':'type="text" inputmode="decimal" maxlength="80"')+' aria-labelledby="prediction-question">'+(c.kind==='written'?'</textarea>':'');$('prediction-response').value=r.response||'';$('prediction-reason').value=r.reason||'';$('experiment-design').value=r.design||'';$('student-explanation').value=r.explanation||'';$('observation-note').value=r.observationDraft||'';
 ['prediction-response','prediction-reason','experiment-design','student-explanation','observation-note'].forEach(id=>$(id).oninput=()=>{r.response=$('prediction-response').value;r.reason=$('prediction-reason').value;r.design=$('experiment-design').value;r.explanation=$('student-explanation').value;r.observationDraft=$('observation-note').value;if(r.phase==='review'&&(id==='student-explanation'||id==='experiment-design')){r.completed=false;r.phase='explore';}save();lock();});
 $('variable-suggestion').textContent='Possible variables: '+t.fields.filter(f=>f.type!=='text'&&f.type!=='textarea'&&!['view','labels','display','filled'].includes(f.key)).slice(0,4).map(f=>f.label).join(' · ')+'. Change one scientific condition at a time; graph views and labels are display settings.';
 document.querySelectorAll('[data-review-check]').forEach(e=>{e.checked=(r.checklist||[]).includes(e.dataset.reviewCheck);});$('student-teacher-link').href=(unitNumber===0?'data-tools.html':'unit-'+unitNumber+'.html')+'#'+current;observations();if(r.phase==='review')feedback();lock();save();}
 const originalRender=render,originalSelect=selectTool;
 render=function(){const r=record();states[current].answers=r.phase==='review';originalRender();lock();save();};
 selectTool=function(key){if(!unitTools.some(([id])=>id===key))key=unitTools[0][0];if(journal.activities[current])save();current=key;const r=record();if(r.state)states[key]=restore(key,r.state);originalSelect(key);mount();try{history.replaceState(null,'','#'+key);}catch{}};
 $('predict-button').onclick=()=>{const r=record(),c=LearningChallenges.get(current,tools[current]);r.response=$('prediction-response').value;r.reason=$('prediction-reason').value;const g=LearningChallenges.grade(c,states[current],r.response);if(!r.response.trim()||!r.reason.trim()||g.kind==='invalid'){$('learning-message').textContent=g.kind==='invalid'?g.message:'Add both a prediction and your reasoning before opening the model.';return;}r.baseline=copy(states[current]);r.phase='explore';r.predictedAt=new Date().toISOString();$('learning-message').textContent='Prediction recorded. Open the model, record a baseline observation, then test one change.';render();mount();};
 $('record-observation').onclick=()=>{const r=record(),note=$('observation-note').value.trim();if(!note){$('learning-message').textContent='Describe a value, pattern or mechanism you observe before recording.';return;}if(!$('error').hidden){$('learning-message').textContent='Resolve the model error before recording evidence.';return;}if(r.observations.length>=12){$('learning-message').textContent='This activity holds 12 observations. Remove one to record another.';return;}r.observations.push({at:new Date().toISOString(),state:copy(states[current]),note,dataSample:sampledRows(data),totalDataRows:data.length});r.observationDraft='';$('observation-note').value='';r.completed=false;r.phase='explore';save();observations();lock();$('learning-message').textContent='Evidence recorded. Compare this setting with another condition.';};
 $('review-button').onclick=()=>{const r=record();r.explanation=$('student-explanation').value;r.design=$('experiment-design').value;r.checklist=Array.from(document.querySelectorAll('[data-review-check]:checked')).map(e=>e.dataset.reviewCheck);const distinct=r.observations.length>=2&&r.observations.some(o=>!sameSettings(o.state,r.observations[0].state));if(!distinct||!r.design.trim()||!r.explanation.trim()||r.checklist.length!==4){$('learning-message').textContent='Before completing: record evidence at two different settings, describe your variable and comparison, explain the result, and check all four review criteria.';return;}r.phase='review';r.completed=true;r.completedAt=new Date().toISOString();render();feedback();lock();save();$('review-panel').scrollIntoView({behavior:'smooth',block:'start'});};
 $('restart-activity').onclick=()=>{if(!confirm('Restart this investigation? Its prediction, observations and explanation will be removed. Export your journal first if you want a copy.'))return;delete journal.activities[current];states[current]=initial(current);selectTool(current);$('learning-message').textContent='Investigation restarted.';};
 $('enlarge-model').onclick=()=>{const focus=document.body.classList.toggle('model-focus');$('enlarge-model').textContent=focus?'Return to investigation':'Enlarge model';$('workspace').scrollIntoView({behavior:'smooth'});};
 $('reset').onclick=()=>{states[current]=initial(current);record().state=copy(states[current]);drawFields();render();};
 $('next-activity').onclick=()=>{const i=unitTools.findIndex(([id])=>id===current);selectTool(unitTools[(i+1)%unitTools.length][0]);$('workspace').scrollIntoView({behavior:'smooth'});};
 document.querySelectorAll('[data-review-check]').forEach(e=>e.onchange=()=>{const r=record();r.checklist=Array.from(document.querySelectorAll('[data-review-check]:checked')).map(x=>x.dataset.reviewCheck);if(r.phase==='review'){r.completed=false;r.phase='explore';}save();lock();});
 function download(content,type,name){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 $('export-journal').onclick=()=>{save();download(JSON.stringify(journal,null,2),'application/json','EAHS-learning-journal.json');};
 $('export-report').onclick=()=>{save();let body=Object.entries(journal.activities).filter(([id])=>tools[id]).map(([id,a])=>{let t=tools[id],c=LearningChallenges.get(id,t),prediction=c.kind==='choice'?c.options[Number(a.response)]||'Not selected':a.response||'';return'<section><h2>Unit '+t.unit+' · '+esc(t.title)+'</h2><p>Status: '+(a.completed?'Completed':'In progress')+'</p><h3>Prediction</h3><p>'+esc(c.question)+'</p><p>'+esc(prediction)+'</p><p>'+esc(a.reason||'')+'</p><h3>Starting conditions</h3><table>'+t.fields.map(f=>'<tr><th>'+esc(f.label)+'</th><td>'+esc((a.baseline||a.state||{})[f.key])+'</td></tr>').join('')+'</table><h3>Experiment design</h3><p>'+esc(a.design||'')+'</p>'+a.observations.map((o,i)=>'<h3>Observation '+(i+1)+'</h3><p>'+esc(o.note)+'</p><table>'+t.fields.map(f=>'<tr><th>'+esc(f.label)+'</th><td>'+esc(o.state[f.key])+'</td></tr>').join('')+'</table>').join('')+'<h3>Explanation</h3><p>'+esc(a.explanation||'')+'</p><h3>Model limitations</h3><p>'+esc(t.assumptions)+'</p></section>';}).join('');download('<!doctype html><html lang="en"><meta charset="utf-8"><title>EAHS Learning Journal</title><style>body{font:16px/1.6 system-ui;max-width:900px;margin:40px auto;padding:20px;color:#14264a}section{break-inside:avoid;border-top:2px solid #b99a55;margin-top:32px}p{white-space:pre-wrap}table{border-collapse:collapse}th,td{border:1px solid #ddd;padding:6px;text-align:left}@media print{body{margin:0}}</style><h1>EAHS Biology Learning Journal</h1><p>Browser-saved investigations. Written explanations are not automatically graded.</p>'+body+'</html>','text/html','EAHS-learning-report.html');};
 if(!unitTools.some(([id])=>id===current))current=unitTools[0][0];selectTool(current);
})();
