const assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm');
class El{
 constructor(doc,tag='div',a={}){this.doc=doc;this.tag=tag;this.id=a.id||'';this.dataset={};for(const[k,v]of Object.entries(a))if(k.startsWith('data-'))this.dataset[k.slice(5).replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]=v;this.value=a.value||'';this.checked=false;this.hidden=false;this.disabled=false;this.children=[];this.attrs=a;this.flags=new Set();this.classList={toggle:(k,v)=>{if(v===undefined)v=!this.flags.has(k);if(v)this.flags.add(k);else this.flags.delete(k);return v;}};}
 set innerHTML(s){this.html=s;this.children=[];for(const m of s.matchAll(/<([a-z][\w-]*)\b([^>]*)>/gi)){const a={};for(const x of m[2].matchAll(/([\w-]+)="([^"]*)"/g))a[x[1]]=x[2];const e=new El(this.doc,m[1],a);this.children.push(e);if(e.id)this.doc.elements[e.id]=e;}}
 get innerHTML(){return this.html||'';}setAttribute(k,v){this.attrs[k]=v;}scrollIntoView(){}click(){this.onclick?.();}
}
function boot(course='ap-chemistry',unit=1,teacher=false,storage=new Map(),offlinePage=null){const elements={},doc={elements,getElementById:id=>elements[id]||null,querySelectorAll:s=>{const kids=Object.values(elements).flatMap(e=>e.children),unique=[...new Set(kids)];if(s.startsWith('[data-')){const key=s.match(/data-([\w-]+)/)[1];return unique.filter(e=>e.dataset[key]!==undefined&&(!s.includes(':checked')||e.checked));}if(s==='#fields input,#fields select')return elements.fields?.children.filter(e=>['input','select'].includes(e.tag))||[];if(s==='.exports button')return ['enlarge','png','svg','csv','print','share'].map(id=>elements[id]);return[];},createElement:tag=>new El(doc,tag)};doc.body=new El(doc);elements.site=new El(doc);elements.site.id='site';const downloads=[];const window={PORTAL:{course,unit,teacher},OFFLINE:!!offlinePage,addEventListener(){},print(){}};const ctx=vm.createContext({window,document:doc,localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},location:{hash:'',search:offlinePage?'?page='+offlinePage:'',href:'https://example.org/unit-'+unit+'.html',protocol:'https:'},history:{replaceState(){}},URL:{createObjectURL:b=>{downloads.push(b);return'blob:test'},revokeObjectURL(){}},URLSearchParams,Blob,setTimeout:f=>f(),confirm:()=>true,prompt:()=>null,console});for(const f of ['models.js','render.js','app.js'])vm.runInContext(fs.readFileSync(__dirname+'/source/'+f,'utf8'),ctx,{filename:f});return{elements,doc,storage,downloads,ctx};}
const b=boot(),e=b.elements;assert.equal(e['figure-wrap'].hidden,true);assert.equal(e['f-mass'].disabled,true);e.predict.onclick();assert.equal(e['figure-wrap'].hidden,true);
e.prediction.value='1';e.reason.value='Mass divided by molar mass gives nearly one mole.';e.predict.onclick();assert.equal(e['figure-wrap'].hidden,false);assert.equal(e['f-mass'].disabled,false);assert.equal(e.prediction.disabled,true);e.observation.value='18 g is about one mole.';e.record.onclick();e['f-mass'].value='36';e['f-mass'].onchange();e.observation.value='Doubling mass doubles moles while molar mass is fixed.';e.record.onclick();e.design.value='Change mass, hold molar mass fixed and compare moles.';e.explanation.value='The amount is proportional to mass because n=m/M. My prediction was close. This assumes a pure substance.';b.doc.querySelectorAll('[data-check]').forEach(c=>c.checked=true);e.complete.onclick();assert.equal(e.review.hidden,false);assert.match(e.feedback.innerHTML,/consistent/);let saved=JSON.parse(b.storage.get('eahs-campus-journal-v1'));assert.equal(saved.activities['ap-chemistry:moles'].completed,true);assert.equal(saved.activities['ap-chemistry:moles'].baseline.mass,18);assert.equal(saved.activities['ap-chemistry:moles'].state.mass,36);
const reload=boot('ap-chemistry',1,false,b.storage);assert.equal(reload.elements.review.hidden,false);assert.match(reload.elements.feedback.innerHTML,/consistent/);e.svg.onclick();e.csv.onclick();e.journal.onclick();e.report.onclick();assert.equal(b.downloads.length,4);e.enlarge.onclick();assert.equal(b.doc.body.flags.has('focus-model'),true);e.enlarge.onclick();assert.equal(b.doc.body.flags.has('focus-model'),false);e.reset.onclick();assert.equal(Number(e['f-mass'].value),18);
let count=0;const M=require('./source/models.js');for(const [course,c]of Object.entries(M.courses)){for(let unit=1;unit<=c.units.length;unit++){const s=boot(course,unit);for(const button of s.doc.querySelectorAll('[data-model]')){button.onclick();assert.equal(s.elements.error.hidden,true,course+'/'+button.dataset.model);assert.equal(s.elements['figure-wrap'].hidden,true);count++;}const t=boot(course,unit,true);assert.equal(t.elements['figure-wrap'].hidden,false);assert.equal(t.elements.svg.disabled,false);assert.equal(t.elements.prediction.disabled,true);}}
const portable=boot('ap-calculus-bc',0,false,new Map(),'teacher-unit-10.html');assert.equal(portable.elements['figure-wrap'].hidden,false);assert.ok(portable.elements['mode-link'].attrs);assert.match(portable.elements['mode-link'].href,/\?page=unit-10.html/);
Promise.all(b.downloads.map(x=>x.text())).then(([svg,csv,json,html])=>{assert.ok(svg.startsWith('<svg'));assert.match(csv,/Moles/);assert.equal(JSON.parse(json).activities['ap-chemistry:moles'].completed,true);assert.ok(html.includes('Starting settings'));assert.ok(html.includes('Doubling mass'));});
console.log(`PASS: ${count} student workspaces, all teacher unit workspaces, prediction gate, manipulation, evidence, baseline feedback, reload, exports, reset and portable routing (DOM fixture, not browser).`);
